"""empty message

Revision ID: 2951c95a1ef9
Revises: b57649a9d8ab
Create Date: 2023-07-31 14:45:24.895013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2951c95a1ef9'
down_revision = 'b57649a9d8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gre_verbal_quant_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gre_awa_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('toefl_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ielts_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('ielts_score')
        batch_op.drop_column('toefl_score')
        batch_op.drop_column('gre_awa_score')
        batch_op.drop_column('gre_verbal_quant_score')

    # ### end Alembic commands ###
