"""empty message

Revision ID: a154d2886d3a
Revises: 
Create Date: 2023-07-31 01:31:30.044799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a154d2886d3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=500), nullable=False),
    sa.Column('first_name', sa.String(length=500), nullable=False),
    sa.Column('last_name', sa.String(length=500), nullable=False),
    sa.Column('primary_email', sa.String(length=500), nullable=False),
    sa.Column('gender', sa.String(length=500), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('secondary_email', sa.String(length=500), nullable=True),
    sa.Column('bsc_year_of_passing', sa.Integer(), nullable=True),
    sa.Column('ms_year_of_passing', sa.Integer(), nullable=True),
    sa.Column('bsc_cgpa', sa.Float(), nullable=True),
    sa.Column('ms_cgpa', sa.Float(), nullable=True),
    sa.Column('bsc_university', sa.String(length=500), nullable=True),
    sa.Column('ms_university', sa.String(length=500), nullable=True),
    sa.Column('github_link', sa.String(length=500), nullable=True),
    sa.Column('linkedin_link', sa.String(length=500), nullable=True),
    sa.Column('website_link', sa.String(length=500), nullable=True),
    sa.Column('current_address', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
