"""empty message

Revision ID: b57649a9d8ab
Revises: 9625a9f672dc
Create Date: 2023-07-31 01:59:34.451978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57649a9d8ab'
down_revision = '9625a9f672dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('doi', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('abstract', sa.String(length=5000), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('venue', sa.String(length=500), nullable=True),
    sa.Column('citation', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi'),
    sa.UniqueConstraint('title')
    )
    op.create_table('student_publication',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'publication_id')
    )
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['primary_email'])
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['github_link'])
        batch_op.create_unique_constraint(None, ['website_link'])
        batch_op.create_unique_constraint(None, ['linkedin_link'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('student_publication')
    op.drop_table('publication')
    # ### end Alembic commands ###
